### ISSUE TITLE
How to setup ELB pure TLS passthru

### ISSUE THREAD

**Issue by NoahKunin** [18F/tls-standards#23]
I guess it should be above the GUI ELB settings? Figure should leave that there for other Fed teams that don't want to roll their own.

**Comment by konklone** [comment]
Updated the doc today in https://github.com/18F/tls-standards/commit/1546c75151f4d099dcbf4a219abfc1f0729f412a.

**Comment by konklone** [comment]
OK, really done in https://github.com/18F/tls-standards/commit/3ba8cd247493460bbba21f399a47f125c283aa3e.
