### ISSUE TITLE
Enable SPDY header compression

### ISSUE THREAD

**Issue by igrigorik** [18F/tls-standards#24]
```
# SPDY header compression (0 for none, 9 for slow/heavy compression). Preferred is 6.
#
# BUT: header compression is flawed and vulnerable in SPDY versions 1 - 3.
# Disable with 0, until using a version of nginx with SPDY 4.
spdy_headers_comp 0;
```

> CRIME can be partially defeated by preventing the use of compression, either at the client end, by the browser disabling the compression of SPDY requests, or by the website preventing the use of data compression on such transactions using the protocol negotiation features of the TLS protocol.  - [source](http://en.wikipedia.org/wiki/CRIME)

Note that CRIME is an attack on *request headers*. All SPDY-capable browsers disable both the TLS protocol compression and SPDY _request header_ compression. The server *can* compress its response headers - that's not a problem. 

FWIW, Google's front-end servers use "6" for the compression setting.

**Comment by konklone** [comment]
Closing in favor of https://github.com/fisma-ready/nginx/issues/7 (better canonical repo than this).
